### SERVER ###
CONNECTION_STRING = 'mariadb+mariadbconnector://root:pass@localhost/mysticc'
SECRET_KEY = ''
HOST = 'http://127.0.0.1:5000/'
MOVE_OBJECT_FREQUENCY_SEC = 0.1

### CLIENT ###
SCREEN = {} 

SCROLL_INTERVAL_MS = 25
SCROLL_PIXEL = 10

TILE_WIDTH = 12
TILE_HEIGHT = 12

MAP_NAME = ''
MAP_CONTAINER_WIDTH  = 0
MAP_CONTAINER_HEIGHT = 0

DIRS = { 'UP': 0, 'RIGHT': 1, 'DOWN': 2, 'LEFT': 3 }

### COMMON ##
DEFAULT_MAP_NAME = 'rootville'